excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://CMJoe100.github.io
title: Harmony
tagline: Brighter Days
description: My awesome blog helps people connect with the realities of life
paginate: 5